### ISSUE TITLE
rake assets:build fails on fresh clone

### ISSUE THREAD

**Issue by wagenet** [parisrb/httpcron#14]
Running `rake assets:build` on a fresh clone was giving me a jammit error. When I ran `jammit -c assets.yml` directly then ran `rake assets:build` it seemed to work.

**Comment by tchak** [comment]
We had only problems with jammit... I will change build system to bpm when I get back from the week-end :)

**Comment by archiloque** [comment]
replaced jammit with sinatra-assetpack
